In [42]:
import pandas as pd
import numpy as np 

pd.options.display.float_format = "{:.2f}".format

In [43]:
base = pd.read_excel("dados/base_engajamento.xlsx")

In [44]:
base = base.drop("Visualizações", axis=1)

In [45]:
base.head()

,Tipo,Data,Curtidas,Comentários,Tags,Pessoas,Campanhas,Carrossel,Interacoes
0,Foto,2021-09-11,2858,16,Loja,N,N,NaN,2874
1,Foto,2021-09-11,2930,28,Loja/Produtos,N,N,NaN,2958
2,Foto,2021-09-11,2807,9,Loja,N,N,NaN,2816
3,Vídeo,2021-09-12,5115,49,Produtos,N,N,NaN,5164
4,Foto,2021-09-13,4392,45,Produtos,S,N,NaN,4437

In [46]:
base.groupby("Tags")["Curtidas"].mean()

Tags
Datas comemorativas                 17975.00
Datas comemorativas/Promoções       29084.00
Dicas de como usar/Novos Produtos    5703.50
Dicas de como usar/Produtos          7586.67
Influenciadores                     15197.29
Loja                                 2832.50
Loja/Produtos                        2930.00
Novos Produtos                      11619.57
Produtos                             5666.92
Promoções                           26645.50
Trends                              22400.67
Trends/Produtos                     12894.00
Name: Curtidas, dtype: float64

In [47]:
texto = "testando nova funçao com split"
texto.split()

['testando', 'nova', 'funçao', 'com', 'split']

In [48]:
base.Tags = base.Tags.str.split("/")
base.head()

,Tipo,Data,Curtidas,Comentários,Tags,Pessoas,Campanhas,Carrossel,Interacoes
0,Foto,2021-09-11,2858,16,[Loja],N,N,NaN,2874
1,Foto,2021-09-11,2930,28,"[Loja, Produtos]",N,N,NaN,2958
2,Foto,2021-09-11,2807,9,[Loja],N,N,NaN,2816
3,Vídeo,2021-09-12,5115,49,[Produtos],N,N,NaN,5164
4,Foto,2021-09-13,4392,45,[Produtos],S,N,NaN,4437

In [49]:
base = base.explode("Tags")
base.head(10)

,Tipo,Data,Curtidas,Comentários,Tags,Pessoas,Campanhas,Carrossel,Interacoes
0,Foto,2021-09-11,2858,16,Loja,N,N,NaN,2874
1,Foto,2021-09-11,2930,28,Loja,N,N,NaN,2958
1,Foto,2021-09-11,2930,28,Produtos,N,N,NaN,2958
2,Foto,2021-09-11,2807,9,Loja,N,N,NaN,2816
3,Vídeo,2021-09-12,5115,49,Produtos,N,N,NaN,5164
4,Foto,2021-09-13,4392,45,Produtos,S,N,NaN,4437
5,Foto,2021-09-17,5359,62,Novos Produtos,N,S,S,5421
6,Foto,2021-09-19,21597,852,Novos Produtos,S,S,NaN,22449
7,Foto,2021-09-25,6346,33,Produtos,N,S,NaN,6379
8,Foto,2021-09-27,6355,89,Produtos,S,N,S,6444

In [50]:
# TOda vez que criar o split ou explode para separar as infos, so pode usar o valor daquelas em que foi separado

# EX, somente Tags

In [51]:
base.groupby("Tags")[["Curtidas", "Comentários"]].mean().sort_values("Curtidas", ascending=False)

                     Curtidas  Comentários
Tags
Promoções            27458.33       531.00
Datas comemorativas  20752.25       343.50
Trends               20024.00       352.25
Influenciadores      15197.29       161.71
Novos Produtos       10304.89       198.56
Dicas de como usar    6833.40       133.60
Produtos              6269.82        94.12
Loja                  2865.00        17.67

In [52]:
base[base.Tags.isnull()]

,Tipo,Data,Curtidas,Comentários,Tags,Pessoas,Campanhas,Carrossel,Interacoes
11,Foto,2021-10-12,17831,391,NaN,S,S,NaN,18222
19,Foto,2021-12-12,16086,268,NaN,S,S,NaN,16354
29,Foto,2022-01-19,8612,142,NaN,S,N,NaN,8754
38,Foto,2022-02-15,17687,213,NaN,S,N,NaN,17900
41,Foto,2022-02-22,12530,90,NaN,S,N,NaN,12620
43,Foto,2022-03-04,24399,266,NaN,S,S,NaN,24665
49,Foto,2022-03-22,9087,106,NaN,S,S,NaN,9193
50,Foto,2022-03-26,16551,186,NaN,S,N,NaN,16737

In [53]:
base.loc[base.Tags.isnull(), "Tags"]

11    NaN
19    NaN
29    NaN
38    NaN
41    NaN
43    NaN
49    NaN
50    NaN
Name: Tags, dtype: object

In [54]:
base.loc[base.Tags.isnull(), "Tags"] = "Sem Tags"

In [55]:
base.groupby("Tags")[["Curtidas", "Comentários"]].mean().sort_values("Curtidas", ascending=False)

                     Curtidas  Comentários
Tags
Promoções            27458.33       531.00
Datas comemorativas  20752.25       343.50
Trends               20024.00       352.25
Sem Tags             15347.88       207.75
Influenciadores      15197.29       161.71
Novos Produtos       10304.89       198.56
Dicas de como usar    6833.40       133.60
Produtos              6269.82        94.12
Loja                  2865.00        17.67

In [57]:
base.loc[base.Tags == "Sem Tags", "Tags"] = np.nan

In [59]:
base.groupby("Tags")[["Curtidas", "Comentários"]].mean().sort_values("Curtidas", ascending=False)

                     Curtidas  Comentários
Tags
Promoções            27458.33       531.00
Datas comemorativas  20752.25       343.50
Trends               20024.00       352.25
Influenciadores      15197.29       161.71
Novos Produtos       10304.89       198.56
Dicas de como usar    6833.40       133.60
Produtos              6269.82        94.12
Loja                  2865.00        17.67

In [64]:
base.groupby(["Pessoas", "Tags"])[["Curtidas", "Comentários"]].mean()

                             Curtidas  Comentários
Pessoas Tags
N       Loja                  2865.00        17.67
        Novos Produtos        5359.00        62.00
        Produtos              4450.67        60.78
S       Datas comemorativas  20752.25       343.50
        Dicas de como usar    6833.40       133.60
        Influenciadores      15197.29       161.71
        Novos Produtos       10923.12       215.62
        Produtos              8316.38       131.62
        Promoções            27458.33       531.00
        Trends               20024.00       352.25

In [65]:
base.groupby(["Pessoas", "Tags"])[["Curtidas", "Comentários"]].mean().sort_values("Curtidas", ascending=False)

                             Curtidas  Comentários
Pessoas Tags
S       Promoções            27458.33       531.00
        Datas comemorativas  20752.25       343.50
        Trends               20024.00       352.25
        Influenciadores      15197.29       161.71
        Novos Produtos       10923.12       215.62
        Produtos              8316.38       131.62
        Dicas de como usar    6833.40       133.60
N       Novos Produtos        5359.00        62.00
        Produtos              4450.67        60.78
        Loja                  2865.00        17.67

In [66]:
base.groupby(["Campanhas", "Tags"])[["Curtidas", "Comentários"]].mean().sort_values("Curtidas", ascending=False)

                               Curtidas  Comentários
Campanhas Tags
S         Promoções            33217.50       490.50
          Trends               22400.67       386.67
          Datas comemorativas  20752.25       343.50
          Influenciadores      18715.40       197.60
N         Promoções            15940.00       612.00
          Trends               12894.00       249.00
S         Novos Produtos       11040.67       323.00
N         Novos Produtos        9937.00       136.33
S         Produtos              9074.00        67.50
N         Dicas de como usar    6833.40       133.60
          Influenciadores       6402.00        72.00
          Produtos              5895.93        97.67
          Loja                  2865.00        17.67